name: nmt_research
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - pip
  - numpy>=1.26.0
  - matplotlib>=3.7.0
  - scikit-learn>=1.3.0
  - h5py>=3.12.1
  - gdown>=5.2.1
  - ipykernel
  - notebook
  - pip:
      - tensorflow==2.19.0
      - tensorflow-hub>=0.16.1
      - nltk>=3.8.1